### ISSUE TITLE
Issues compiling

### ISSUE THREAD

**Issue by bwhaley7** [LukeGoule/gm#1]
Could only get this to compile in debug32. When injected it seemed as if the menu was incomplete and missing half of the ui. Any idea how to fix?

**Comment by LukeGoule** [comment]
Hi. My sincerest apologies for not responding for well over 2 years.

I never really finished this as it was just a test for implementing an SDK for gmod. This is entirely a 32 bit sdk and I won't bother updating anything for 64 bit. Feel free to try lol.

FYI - this was a crappy copy-paste of another project I worked on for CS:GO but ported to work with garrys mod as best as possible, a bunch of the cs hacks were useless in here,
